/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reports;

import ConnectionDB.ControlDB;
import ObjectsDB.Order;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user-ubunto
 */
public class Report4 extends javax.swing.JFrame {
    private ArrayList<Order> orders;
    private ControlDB control;
    private DefaultTableModel dtmOrder;
    
    /**
     * Creates new form Report4
     */
    public Report4(ControlDB control1, String codeStore) {
        initComponents();
        this.control = control1;
        this.dtmOrder = (DefaultTableModel)this.jTable1.getModel();
        this.orders = control1.setReport4(codeStore);
        setProductsTable();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Listado de todos los pedidos que salieron de la tienda y están en tránsito.");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Fecha de Entrada", "Fecha de Salida", "Total", "Adelanto", "Nombre del Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExportReport1 export = new ExportReport1();
        export.setOrders(this.orders);
        export.exportReport("Listado de todos los pedidos que salieron de la tienda y están en tránsito.");
    }//GEN-LAST:event_jButton1ActionPerformed

     public void setProductsTable(){
        cleanTableProducts();
        String code = "";
        String dateOrder = "";
        String dateReceipt = "";
        double total = 0;
        double advance = 0;
        String codeClient;
        
        int sizeOrders = this.orders.size();
        for (int i = 0; i < sizeOrders; i++) {
            code = this.orders.get(i).getCode();
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            dateOrder = sdf.format(this.orders.get(i).getDateOrder());
            dateReceipt = sdf.format(this.orders.get(i).getDateReceipt());
            total = this.orders.get(i).getTotal();
            advance = this.orders.get(i).getAdvance();
            codeClient = this.orders.get(i).getClientNIT();
            
            this.dtmOrder.addRow(new Object[]{code,dateOrder,dateReceipt,total,advance,codeClient});
        }                
        
        this.jTable1.setModel(dtmOrder);
    }
    
    public void cleanTableProducts(){
        int filas=this.jTable1.getRowCount();
        for (int i = 0;filas>i; i++) {
            this.dtmOrder.removeRow(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
