/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIUser;

/**
 *
 * @author user-ubunto
 */
public class fClient extends javax.swing.JFrame {

    private String IDClient;
    
    /**
     * Creates new form fClient
     */
    public fClient(String IdClient) {
        initComponents();
        this.IDClient = IdClient;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonOrders = new javax.swing.JButton();
        ButtonCatalog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonOrders.setText("Revisar Pedidos");
        ButtonOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOrdersActionPerformed(evt);
            }
        });

        ButtonCatalog.setText("Catalogo");
        ButtonCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCatalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(ButtonCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(ButtonOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOrdersActionPerformed
        fOrdersClient fordersClient = new fOrdersClient();
        fordersClient.setVisible(true);
    }//GEN-LAST:event_ButtonOrdersActionPerformed

    private void ButtonCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCatalogActionPerformed
        fCatalogClient fcatalogClient = new fCatalogClient();
        fcatalogClient.setVisible(true);
    }//GEN-LAST:event_ButtonCatalogActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCatalog;
    private javax.swing.JButton ButtonOrders;
    // End of variables declaration//GEN-END:variables
}
