/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIEmployee;

import ConnectionDB.ControlDB;
import GUIStart.fChooseDateStore;
import java.util.Date;

/**
 *
 * @author user-ubunto
 */
public class fEmployee extends javax.swing.JFrame {
    private Date actualDate;
    private ControlDB control;
    private String codeStore;
    /**
     * Creates new form FrameEmployee
     */
    public fEmployee(ControlDB control1, String codeStore, Date actualDate) {
        initComponents();
        this.control = control1;
        this.codeStore = codeStore;
        this.actualDate = actualDate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonSell = new javax.swing.JButton();
        ButtonOrder = new javax.swing.JButton();
        ButtonReports = new javax.swing.JButton();
        ButtonNew = new javax.swing.JButton();
        ButtonChangeDate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonSell.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonSell.setText("Vender");
        ButtonSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSellActionPerformed(evt);
            }
        });

        ButtonOrder.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonOrder.setText("Realizar Pedido");
        ButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOrderActionPerformed(evt);
            }
        });

        ButtonReports.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonReports.setText("Reportes");

        ButtonNew.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonNew.setText("Ingresar y Modificar Datos");
        ButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewActionPerformed(evt);
            }
        });

        ButtonChangeDate.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonChangeDate.setText("Cambiar fecha o tienda");
        ButtonChangeDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChangeDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(ButtonReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ButtonChangeDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonNew, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ButtonSell, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(120, 120, 120))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonChangeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonReports, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSellActionPerformed
        fSell newSell = new fSell();
        newSell.setVisible(true);
    }//GEN-LAST:event_ButtonSellActionPerformed

    private void ButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOrderActionPerformed
        fOrder newOrder = new fOrder();
        newOrder.setVisible(true);
    }//GEN-LAST:event_ButtonOrderActionPerformed

    private void ButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewActionPerformed
        fNewData newNewData = new fNewData(this.control, this.codeStore);
        newNewData.setVisible(true);
        
    }//GEN-LAST:event_ButtonNewActionPerformed

    private void ButtonChangeDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChangeDateActionPerformed
        fChooseDateStore chooseDate = new fChooseDateStore(this.control,this.actualDate,this.codeStore);
        chooseDate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonChangeDateActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonChangeDate;
    private javax.swing.JButton ButtonNew;
    private javax.swing.JButton ButtonOrder;
    private javax.swing.JButton ButtonReports;
    private javax.swing.JButton ButtonSell;
    // End of variables declaration//GEN-END:variables
}
