/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIEmployee;

import ConnectionDB.ControlDB;
import ObjectsDB.ShippingTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user-ubunto
 */
public class fNewTime extends javax.swing.JFrame {
    private ControlDB control;
    /**
     * Creates new form fNewTime
     */
    public fNewTime(ControlDB control1) {
        initComponents();
        this.control = control1;
        this.control.setCodeStoreCombobox(this.ComboBoxStore1);
        this.control.setCodeStoreCombobox(this.ComboBoxStore2); 
        this.buttonGroup1.add(jRadioButton1);
        this.buttonGroup1.add(jRadioButton2);
        this.jRadioButton1.setSelected(true);
        setTime();
        setInTableShippingTimeByName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxStore1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxStore2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ButtonSaveTime = new javax.swing.JButton();
        TextFieldDays = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tienda 1");

        ComboBoxStore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxStore1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tienda 2");

        ComboBoxStore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxStore2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tiempo");

        ButtonSaveTime.setText("Guardar Tiempo");
        ButtonSaveTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveTimeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tienda 1", "Tienda 2", "Tiempo en dias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jRadioButton1.setText("Nombres");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Codigos");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxStore2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(ComboBoxStore1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(ButtonSaveTime, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(TextFieldDays))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jRadioButton2)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxStore1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxStore2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonSaveTime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSaveTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveTimeActionPerformed
        String store1 = String.valueOf(this.ComboBoxStore1.getSelectedItem());
        String store2 = String.valueOf(this.ComboBoxStore2.getSelectedItem());
        int timeInsert = 0;
        if (this.TextFieldDays.getText().equals("") == false){
            timeInsert = Integer.parseInt(this.TextFieldDays.getText());        
            if (verifyStores() == true) {
                int time =0;
                time = this.control.existRelationShippingTime(store1, store2);
                if (time == 0) 
                    this.control.insertShippingTime(store1, store2, timeInsert);
                else
                    this.control.updateShippingTime(store1, store2, timeInsert);
            }
        }
        setTime();
        setInTableShippingTimeByName();
    }//GEN-LAST:event_ButtonSaveTimeActionPerformed

    private void ComboBoxStore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxStore1ActionPerformed
        setTime();
    }//GEN-LAST:event_ComboBoxStore1ActionPerformed

    private void ComboBoxStore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxStore2ActionPerformed
        setTime();
    }//GEN-LAST:event_ComboBoxStore2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        verifyRadioButtons();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        verifyRadioButtons();
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    private void verifyRadioButtons(){
        if (this.jRadioButton1.isSelected()) {
            setInTableShippingTimeByName();
        }else if(this.jRadioButton2.isSelected()){
            setInTableShippingTimeByCode();
        }
    }
    
    public boolean verifyStores(){
        boolean isReady = true;
        String store1 = String.valueOf(this.ComboBoxStore1.getSelectedItem());
        String store2 = String.valueOf(this.ComboBoxStore2.getSelectedItem());
        
        if (store1.equalsIgnoreCase(store2))
            isReady = false;
            
        return isReady;
    }
    
    public void setTime(){
        String store1 = String.valueOf(this.ComboBoxStore1.getSelectedItem());
        String store2 = String.valueOf(this.ComboBoxStore2.getSelectedItem());
        int time =0;
        time = this.control.existRelationShippingTime(store1, store2);
        if (time != 0) {
            time = this.control.searchDaysShipping(String.valueOf(time));
            this.TextFieldDays.setText(String.valueOf(time));
        }else
            this.TextFieldDays.setText("");
    }
    
    public void setInTableShippingTimeByName(){
        clearTable();
        DefaultTableModel dtmShippingTime = (DefaultTableModel) this.jTable1.getModel();
        ArrayList<ShippingTime> shippingTimes = this.control.getAllShippingTime();
        String nameStore1 = "";
        String nameStore2 = "";
        for (int i = 0; i < shippingTimes.size(); i++) {
            nameStore1 = this.control.getNameStoreByCode(shippingTimes.get(i).getStoreCodeOut());
            nameStore2 = this.control.getNameStoreByCode(shippingTimes.get(i).getStoreCodeEnter());
            dtmShippingTime.addRow(new Object[]{nameStore1,nameStore2,shippingTimes.get(i).getDaysTime()});
        }
        this.jTable1.setModel(dtmShippingTime);
    }
    
    public void setInTableShippingTimeByCode(){
        clearTable();
        DefaultTableModel dtmShippingTime = (DefaultTableModel) this.jTable1.getModel();
        ArrayList<ShippingTime> shippingTimes = this.control.getAllShippingTime();
        for (int i = 0; i < shippingTimes.size(); i++) {
            dtmShippingTime.addRow(new Object[]{shippingTimes.get(i).getStoreCodeOut(),shippingTimes.get(i).getStoreCodeEnter(),shippingTimes.get(i).getDaysTime()});
        }
        this.jTable1.setModel(dtmShippingTime);
    }
    
    public void clearTable(){
        DefaultTableModel dtmShippingTime = (DefaultTableModel) this.jTable1.getModel();
        int filas=this.jTable1.getRowCount();
        for (int i = 0;filas>i; i++) {
            dtmShippingTime.removeRow(0);
        }
        this.jTable1.setModel(dtmShippingTime);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSaveTime;
    private javax.swing.JComboBox<String> ComboBoxStore1;
    private javax.swing.JComboBox<String> ComboBoxStore2;
    private javax.swing.JTextField TextFieldDays;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
