/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIEmployee;

import ConnectionDB.ControlDB;
import ObjectsDB.Client;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user-ubunto
 */
public class fNewClient extends javax.swing.JFrame {

    private DefaultTableModel dtmClient;
    private TableRowSorter tableRowSorterClient;
    private String NITClientChange;
    private ControlDB control;
    ArrayList<Client> clients;
    
    /**
     * Creates new form fNewClient
     */
    public fNewClient(ControlDB control1) {
        initComponents();
        this.control = control1;
        dtmClient = (DefaultTableModel) this.TableClient.getModel();
        cleanTextBox();
        this.clients = this.control.setClients();
        setClients();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelName = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        LabelDPI = new javax.swing.JLabel();
        TextFieldDpi = new javax.swing.JTextField();
        LabelPhone = new javax.swing.JLabel();
        TextFieldPhone = new javax.swing.JTextField();
        LabelCredit = new javax.swing.JLabel();
        TextFieldCredit = new javax.swing.JTextField();
        LabelNIT = new javax.swing.JLabel();
        TextFieldNit = new javax.swing.JTextField();
        LabelEMail = new javax.swing.JLabel();
        TextFieldEMail = new javax.swing.JTextField();
        LabelDiretion = new javax.swing.JLabel();
        TextFieldAddress = new javax.swing.JTextField();
        ButtonSaveClient = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableClient = new javax.swing.JTable();
        TextFieldFilterClient = new javax.swing.JTextField();
        ButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelName.setText("Nombre del cliente*");

        LabelDPI.setText("DPI");

        TextFieldDpi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldDpiKeyTyped(evt);
            }
        });

        LabelPhone.setText("Telefono*");

        TextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldPhoneKeyTyped(evt);
            }
        });

        LabelCredit.setText("Credito de Compra");

        TextFieldCredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldCreditKeyTyped(evt);
            }
        });

        LabelNIT.setText("NIT*");

        LabelEMail.setText("Correo Electronico");

        LabelDiretion.setText("Direccion");

        ButtonSaveClient.setText("Guardar Cliente");
        ButtonSaveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveClientActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel6.setText("Clientes Guardados");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel9.setText("Filtrar");
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldFilterClientKeyTyped(evt);
            }
        });

        TableClient.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        TableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Juan", "11111", "0101", "800", "3424324", "adfa", "11saa"},
                {"MAria", "22222", "9817", "0", "5453543", "fdfd", "22sss"},
                {"Pedro", "3333", "7871", "1000", "6546465", "fhgfh", null}
            },
            new String [] {
                "Nombre", "NIT", "DPI", "Credito", "Telefono", "Correo", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableClient);

        TextFieldFilterClient.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        TextFieldFilterClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldFilterClientKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldFilterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(TextFieldFilterClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        ButtonDelete.setText("Eliminar");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TextFieldCredit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(LabelName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelDPI, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelPhone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TextFieldName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TextFieldDpi, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TextFieldPhone, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(LabelCredit))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelDiretion)
                    .addComponent(LabelEMail)
                    .addComponent(LabelNIT)
                    .addComponent(TextFieldNit)
                    .addComponent(TextFieldEMail)
                    .addComponent(TextFieldAddress)
                    .addComponent(ButtonSaveClient, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNIT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelDPI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldDpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelEMail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelPhone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelDiretion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelCredit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonSaveClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonDelete)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldDpiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldDpiKeyTyped
        validateOnlyNumbers(evt);
    }//GEN-LAST:event_TextFieldDpiKeyTyped

    private void TextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldPhoneKeyTyped
        validateOnlyNumbers(evt);
    }//GEN-LAST:event_TextFieldPhoneKeyTyped

    private void TextFieldCreditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldCreditKeyTyped
        validateOnlyNumbers(evt);
    }//GEN-LAST:event_TextFieldCreditKeyTyped

    private void ButtonSaveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveClientActionPerformed
        if (this.reviewRequiredFields() == true ) {
            String NIT = this.TextFieldNit.getText();
            String name = this.TextFieldName.getText();
            String phone = this.TextFieldPhone.getText();
            String DPI = null;
            String credit = "0";
            String email = null;
            String address = null;
            if (this.TextFieldDpi.getText().equals("") == false)
                DPI = this.TextFieldDpi.getText();            
            if (this.TextFieldCredit.getText().equals("") == false)
                credit = this.TextFieldCredit.getText();
            if (this.TextFieldEMail.getText().equals("") == false)
                email= this.TextFieldEMail.getText();
            if (this.TextFieldAddress.getText().equals("") == false)
                address = this.TextFieldAddress.getText();
            
            if (this.NITClientChange.equals("")) {
                if (reviewExistCode()) {
                    this.control.insertClient(NIT, name, phone, DPI, credit, email, address);
                    cleanTextBox();
                }else
                    JOptionPane.showMessageDialog(this,"No puedes insertar porque ya existe un cliente con ese codigo");
            }else{                
                this.control.updateClient(this.NITClientChange, name, phone, DPI, credit, email, address);                
                cleanTextBox();
            }
            this.clients = this.control.setClients();
            setClients();                        
        }
    }//GEN-LAST:event_ButtonSaveClientActionPerformed

    private void TableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClientMouseClicked
        int select = this.TableClient.rowAtPoint(evt.getPoint());
        
        this.TextFieldName.setText(String.valueOf(this.TableClient.getValueAt(select,0)));
        this.TextFieldNit.setText(String.valueOf(this.TableClient.getValueAt(select,1)));
        this.TextFieldDpi.setText(String.valueOf(this.TableClient.getValueAt(select,2)));
        this.TextFieldCredit.setText(String.valueOf(this.TableClient.getValueAt(select,3)));
        this.TextFieldPhone.setText(String.valueOf(this.TableClient.getValueAt(select,4)));
        this.TextFieldEMail.setText(String.valueOf(this.TableClient.getValueAt(select,5)));
        this.TextFieldAddress.setText(String.valueOf(this.TableClient.getValueAt(select,6)));        
        
        this.NITClientChange = this.TextFieldNit.getText();
    }//GEN-LAST:event_TableClientMouseClicked

    private void TextFieldFilterClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldFilterClientKeyTyped
        /*This is the filter of the rows of the table that
        *contains the Client, you can filter the column 0and 1
        */
        this.TextFieldFilterClient.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent ke){
                tableRowSorterClient.setRowFilter(RowFilter.regexFilter("(?i)"+TextFieldFilterClient.getText(), 0,1));
            }
        });

        tableRowSorterClient = new TableRowSorter(dtmClient);
        this.TableClient.setRowSorter(tableRowSorterClient);
    }//GEN-LAST:event_TextFieldFilterClientKeyTyped

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        //TODO Delete client with the NIT.
        
        
        this.NITClientChange = "";
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private boolean reviewRequiredFields(){
        this.setColorsLabels();
        boolean isReady = true;
        if (this.TextFieldName.getText().isEmpty() == true) {
            isReady= false;
            this.LabelName.setForeground(Color.red);            
        }
        if (this.TextFieldPhone.getText().isEmpty() == true) {
            isReady= false;
            this.LabelPhone.setForeground(Color.red);
        }
        if (this.TextFieldNit.getText().isEmpty() == true) {
            isReady= false;
            this.LabelNIT.setForeground(Color.red);
        }       
        return isReady;
    }
    
    private void setColorsLabels(){        
        this.LabelName.setForeground(Color.black);
        this.LabelPhone.setForeground(Color.black);
        this.LabelNIT.setForeground(Color.black);        
    }
    
    /**
     * This method is used by textfields so that the user does 
     * not enter any character that is not a digit.
     *
     * @param evt
    */
    public void validateOnlyNumbers(java.awt.event.KeyEvent evt){
        char validate = evt.getKeyChar();
        if (Character.isDigit(validate) == false) {
            evt.consume();
        }        
    }
    
    public void cleanTextBox(){
        this.TextFieldAddress.setText("");
        this.TextFieldName.setText("");
        this.TextFieldNit.setText("");
        this.TextFieldDpi.setText("");
        this.TextFieldEMail.setText("");
        this.TextFieldPhone.setText("");
        this.TextFieldCredit.setText("");
        this.NITClientChange = "";
        
    }
    
    public void setClients(){
        cleanTable();
        String NIT = "";
        String name = "";
        String phone = "";
        String DPI = "";
        double credit = 0;
        String email = "";
        String address = "";
        
        int sizeClients = this.clients.size();
        for (int i = 0; i < sizeClients; i++) {
            NIT = this.clients.get(i).getNIT();
            name = this.clients.get(i).getName();
            phone = this.clients.get(i).getPhone();
            DPI = this.clients.get(i).getDPI();
            credit = this.clients.get(i).getCredit();
            email = this.clients.get(i).getEmail();
            address = this.clients.get(i).getAddress();
                       
            this.dtmClient.addRow(new Object[]{name, NIT, DPI, credit, phone , email, address});
        }                
        
        this.TableClient.setModel(dtmClient);
    }
    
    public void cleanTable(){
        int filas=this.TableClient.getRowCount();
        for (int i = 0;filas>i; i++) {
            this.dtmClient.removeRow(0);
        }
    }
    
    private boolean reviewExistCode(){
        ArrayList<String> codes = this.control.allCodesClients();
        for (int i = 0; i < codes.size(); i++) {
            String code = this.TextFieldNit.getText();
            if (codes.get(i).equals(code)) {
                return false;
            }            
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonSaveClient;
    private javax.swing.JLabel LabelCredit;
    private javax.swing.JLabel LabelDPI;
    private javax.swing.JLabel LabelDiretion;
    private javax.swing.JLabel LabelEMail;
    private javax.swing.JLabel LabelNIT;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPhone;
    private javax.swing.JTable TableClient;
    private javax.swing.JTextField TextFieldAddress;
    private javax.swing.JTextField TextFieldCredit;
    private javax.swing.JTextField TextFieldDpi;
    private javax.swing.JTextField TextFieldEMail;
    private javax.swing.JTextField TextFieldFilterClient;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldNit;
    private javax.swing.JTextField TextFieldPhone;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
