/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIEmployee;

/**
 *
 * @author user-ubunto
 */
public class fNewData extends javax.swing.JFrame {

    /**
     * Creates new form fNewData
     */
    public fNewData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonNewTime = new javax.swing.JButton();
        ButtonNewClient = new javax.swing.JButton();
        ButtonNewEmployee = new javax.swing.JButton();
        ButtonNewStore = new javax.swing.JButton();
        ButtonNewProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonNewTime.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonNewTime.setText("Ingresar Nuevo Tiempo");
        ButtonNewTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewTimeActionPerformed(evt);
            }
        });

        ButtonNewClient.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonNewClient.setText("Clientes");
        ButtonNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewClientActionPerformed(evt);
            }
        });

        ButtonNewEmployee.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonNewEmployee.setText("Empleados");
        ButtonNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewEmployeeActionPerformed(evt);
            }
        });

        ButtonNewStore.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonNewStore.setText("Tiendas");
        ButtonNewStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewStoreActionPerformed(evt);
            }
        });

        ButtonNewProduct.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        ButtonNewProduct.setText("Productos");
        ButtonNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ButtonNewTime, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(ButtonNewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(ButtonNewClient, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(ButtonNewStore, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(ButtonNewEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(ButtonNewStore, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonNewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonNewTime, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNewTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewTimeActionPerformed
        fNewTime newTime = new fNewTime();
        newTime.setVisible(true);
    }//GEN-LAST:event_ButtonNewTimeActionPerformed

    private void ButtonNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewClientActionPerformed
        fNewClient newClient = new fNewClient();
        newClient.setVisible(true);
    }//GEN-LAST:event_ButtonNewClientActionPerformed

    private void ButtonNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewEmployeeActionPerformed
        fNewEmployee newEmployee = new fNewEmployee();
        newEmployee.setVisible(true);
    }//GEN-LAST:event_ButtonNewEmployeeActionPerformed

    private void ButtonNewStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewStoreActionPerformed
        fNewStore newStore = new fNewStore();
        newStore.setVisible(true);
    }//GEN-LAST:event_ButtonNewStoreActionPerformed

    private void ButtonNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewProductActionPerformed
        fNewProduct newProduct = new fNewProduct();
        newProduct.setVisible(true);
    }//GEN-LAST:event_ButtonNewProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonNewClient;
    private javax.swing.JButton ButtonNewEmployee;
    private javax.swing.JButton ButtonNewProduct;
    private javax.swing.JButton ButtonNewStore;
    private javax.swing.JButton ButtonNewTime;
    // End of variables declaration//GEN-END:variables
}
